# This is a basic workflow to help you get started with Actions

name: CreatePDF

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install wkhtmltopdf
      run: |
        wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.5/wkhtmltox_0.12.5-1.bionic_amd64.deb
        sudo apt install ./wkhtmltox_0.12.5-1.bionic_amd64.deb

    - name: Install PanDoc
      uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: '2.7.3'

    - name: Run PanDoc
      run: pandoc -s -t html -V margin-top=10 -V margin-left=10 -V margin-right=10 -V margin-bottom=10 -c pandoc.css index.md -o pdfs/resume.pdf

    # - name: Create PDF via PanDoc
    #   uses: docker://pandoc/core:2.9
    #   with:
    #     args: >-
    #       -s
    #       -t html
    #       -V margin-top=10 -V margin-left=10 -V margin-right=10 -V margin-bottom=10
    #       -c pandoc.css
    #       index.md -o pdfs/resume.pdf --metadata pagetitle="Harrison Clark | Resume"

          
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pdfs/*
        git commit -m "Update PDF" -a
  
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
