# This is a basic workflow to help you get started with Actions

name: CreatePDF

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
    
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # - name: Copy files
    #   run: |
    #     mkdir doc
    #     cp index.md doc/resume.md
    
    # - name: Create PDF and HTML
    #   uses: BaileyJM02/markdown-to-pdf@v1.0.0
    #   with:
    #     # (Path) The location of the folder containing your .md or .markdown files
    #     input_dir: doc
    #     output_dir: pdfs
    #     # (Path) The location of the folder containing your images, this should be the route of all images
    #     # (String) The path you use to import your images that can be replaced with the server URL
    #     # (Path) The location of the folder you want to place the built files
    #     # (Boolean) Whether to also create a .html file
    #     # (File) The location of the CSS file you want to use as the theme
    #     # (File) The location of the CSS file you want to use as the code snipped highlight theme
    #     # (File) The location of the HTML/Mustache file you want to use as the HTML template

    - name: Install wkhtmltopdf
      run: sudo apt-get install xvfb libfontconfig wkhtmltopdf

    - name: Create PDF via PanDoc
      uses: docker://pandoc/core:2.9
      with:
        args: >-
          -s
          -t html
          -V margin-top=10 -V margin-left=10 -V margin-right=10 -V margin-bottom=10
          -c pandoc.css
          index.md -o pdfs/resume.pdf --metadata pagetitle="Harrison Clark | Resume"

          
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pdfs/*
        git commit -m "Update PDF" -a
  
    - name: GitHub Push
      uses: ad-m/github-push-action@v0.5.0
      with:
        # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
